use std::{
    collections::{HashMap, HashSet},
    env, fs,
    path::PathBuf,
};

#[derive(Debug)]
struct DocExample {
    name: String,
    syntax: String,
    mode: Mode,
    source: String,
}

#[derive(Clone, Copy, Debug)]
enum Mode {
    Check,
    Run,
}

impl Mode {
    fn parse(value: &str, line: usize) -> Self {
        match value {
            "check" => Self::Check,
            "run" => Self::Run,
            _ => panic!(
                "README.md:{line}: unsupported doc example mode `{value}`; use `check` or `run`"
            ),
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let readme = manifest_dir.join("../..").join("README.md");
    println!("cargo:rerun-if-changed={}", readme.display());

    let markdown = fs::read_to_string(&readme)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", readme.display()));
    let examples = extract_examples(&markdown);
    let generated = generate_tests(&examples);
    let output =
        PathBuf::from(env::var("OUT_DIR").expect("output directory")).join("readme_doc_tests.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", output.display()));
}

fn extract_examples(markdown: &str) -> Vec<DocExample> {
    let mut examples = vec![];
    let mut names = HashSet::new();
    let mut lines = markdown.lines().enumerate();

    while let Some((line_index, line)) = lines.next() {
        let Some(info) = line.strip_prefix("```") else {
            continue;
        };
        let line_number = line_index + 1;
        let Some((syntax, name, mode)) = parse_fence_info(info, line_number) else {
            continue;
        };

        let mut source = String::new();
        let mut closed = false;
        for (_, source_line) in lines.by_ref() {
            if source_line == "```" {
                closed = true;
                break;
            }
            source.push_str(source_line);
            source.push('\n');
        }
        assert!(
            closed,
            "README.md:{line_number}: unterminated doc example `{name}`"
        );
        assert!(
            !source.trim().is_empty(),
            "README.md:{line_number}: doc example `{name}` is empty"
        );
        assert!(
            names.insert(name.clone()),
            "README.md:{line_number}: duplicate doc example name `{name}`"
        );
        examples.push(DocExample {
            name,
            syntax,
            mode,
            source,
        });
    }

    examples
}

fn parse_fence_info(info: &str, line: usize) -> Option<(String, String, Mode)> {
    let mut tokens = info.split_whitespace();
    let syntax = tokens.next()?;
    if !matches!(syntax, "lisp" | "jisp" | "json" | "yaml" | "yml") {
        return None;
    }

    let attributes = tokens.map(|token| {
        token.split_once('=').unwrap_or_else(|| {
            panic!("README.md:{line}: unsupported doc example attribute `{token}`")
        })
    });
    let mut values = HashMap::new();
    for (key, value) in attributes {
        assert!(
            matches!(key, "test" | "mode"),
            "README.md:{line}: unsupported doc example attribute `{key}`"
        );
        assert!(
            values.insert(key, value).is_none(),
            "README.md:{line}: repeated doc example attribute `{key}`"
        );
    }

    let name = values.get("test")?;
    assert!(
        !name.is_empty(),
        "README.md:{line}: doc example needs a non-empty `test` name"
    );
    let mode = values
        .get("mode")
        .map_or(Mode::Check, |mode| Mode::parse(mode, line));
    Some((syntax.to_owned(), (*name).to_owned(), mode))
}

fn generate_tests(examples: &[DocExample]) -> String {
    let mut output = String::from("// @generated by crates/jisp/build.rs; do not edit.\n\n");
    let mut identifiers = HashSet::new();

    for example in examples {
        let identifier = unique_identifier(&format!("readme_{}", example.name), &mut identifiers);
        let extension = match example.syntax.as_str() {
            "lisp" | "jisp" => "lisp",
            "json" => "json",
            "yaml" | "yml" => "yaml",
            _ => unreachable!("syntax was validated while extracting examples"),
        };
        let file = format!("README.md#{}.{}", example.name, extension);
        let invoke = match example.mode {
            Mode::Check => "jisp::check(FILE, SOURCE).map(|_| ())",
            Mode::Run => "jisp::run_main(FILE, SOURCE).map(|_| ())",
        };
        output.push_str(&format!(
            "#[test]\nfn {identifier}() {{\n    const FILE: &str = {file:?};\n    const SOURCE: &str = {source:?};\n    {invoke}.unwrap_or_else(|error| panic!(\"README example `{name}` failed: {{error}}\"));\n}}\n\n",
            source = example.source,
            name = example.name,
        ));
    }

    output
}

fn unique_identifier(name: &str, identifiers: &mut HashSet<String>) -> String {
    let base: String = name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character
            } else {
                '_'
            }
        })
        .collect();
    let base = if base.is_empty() {
        "doc_example"
    } else {
        &base
    };
    let mut candidate = base.to_owned();
    let mut suffix = 2;
    while !identifiers.insert(candidate.clone()) {
        candidate = format!("{base}_{suffix}");
        suffix += 1;
    }
    candidate
}
