repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test --workspace --exclude jisp-macros
        language: system
        pass_filenames: false
